version: '2'

volumes:
    orderer.example.com:
    peer0.org1.example.com:
    peer1.org1.example.com:
    peer2.org1.example.com:

networks:
    fabric:

services:

    ca.org1.example.com:
        image: hyperledger/fabric-ca
        container_name: ca.org1.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e67280ddfddeb076c72710bbfaa33ba6ec70d7f062975ce90e2a97e95169c1c0_sk
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e67280ddfddeb076c72710bbfaa33ba6ec70d7f062975ce90e2a97e95169c1c0_sk
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        networks:
            - fabric

    orderer.example.com:
        extends:
            file: nodebase.yaml
            service: orderer
        container_name: orderer.example.com
        environment:
            - ORERDER_LOGGING_GRPC=DEBUG
            - ORDERER_HOST=orderer.example.com
            - ORDERER_ABSOLUTEMAXBYTES=10 MB
            - ORDERER_PREFERREDMAXBYTES=512 KB      
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        extra_hosts:
            - "orderer.example.com:${NODE1}"
            - "peer0.org1.example.com:${NODE1}"
            - "peer1.org1.example.com:${NODE1}"
            - "peer2.org1.example.com:${NODE1}"
            - "peer0.org2.example.com:${NODE2}"
            - "peer1.org2.example.com:${NODE2}"
            - "peer2.org2.example.com:${NODE2}"
            - "peer0.org3.example.com:${NODE3}"
            - "peer1.org3.example.com:${NODE3}"
            - "peer2.org3.example.com:${NODE3}"
        volumes:
            - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/msp
            - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/tls
            - ./channel-artifacts/:/var/hyperledger/configs
        networks:
            - fabric
        depends_on:
            - ca.org1.example.com
        ports:
          - 7050:7050

    peer0.org1.example.com:
        container_name: peer0.org1.example.com
        cap_add:
            - NET_ADMIN
        extends:
            file: nodebase.yaml
            service: peer
        environment:
            - CORE_LOGGING_GRPC=DEBUG
            - CORE_PEER_ID=peer0.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.org1.example.com:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
        extra_hosts:
            - "orderer.example.com:${NODE1}"
            - "peer0.org2.example.com:${NODE2}"
            - "peer1.org2.example.com:${NODE2}"
            - "peer2.org2.example.com:${NODE2}"
            - "peer0.org3.example.com:${NODE3}"
            - "peer1.org3.example.com:${NODE3}"
            - "peer2.org3.example.com:${NODE3}"
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
            - peer0.org1.example.com:/var/hyperledger/production
        ports:
            - 7051:7051
        mem_limit: '3G'
        cpuset: 1,2,3,4
        networks:
            - fabric
        
    peer1.org1.example.com:
        container_name: peer1.org1.example.com
        cap_add:
            - NET_ADMIN
        extends:
            file: nodebase.yaml
            service: peer
        environment:
            - CORE_LOGGING_GRPC=DEBUG
            - CORE_PEER_ID=peer1.org1.example.com
            - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
            - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:7052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.org1.example.com:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
        extra_hosts:
            - "orderer.example.com:${NODE1}"
            - "peer0.org2.example.com:${NODE2}"
            - "peer1.org2.example.com:${NODE2}"
            - "peer2.org2.example.com:${NODE2}"
            - "peer0.org3.example.com:${NODE3}"
            - "peer1.org3.example.com:${NODE3}"
            - "peer2.org3.example.com:${NODE3}"
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
            - peer1.org1.example.com:/var/hyperledger/production
        ports:
            - 8051:7051
        mem_limit: '2G'
        cpuset: 5,6
        networks:
            - fabric

    peer2.org1.example.com:
        container_name: peer2.org1.example.com
        cap_add:
            - NET_ADMIN
        extends:
            file: nodebase.yaml
            service: peer
        environment:
            - CORE_LOGGING_GRPC=DEBUG
            - CORE_PEER_ID=peer2.org1.example.com
            - CORE_PEER_ADDRESS=peer2.org1.example.com:7051
            - CORE_PEER_CHAINCODEADDRESS=peer2.org1.example.com:7052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
        extra_hosts:
            - "orderer.example.com:${NODE1}"
            - "peer0.org2.example.com:${NODE2}"
            - "peer1.org2.example.com:${NODE2}"
            - "peer2.org2.example.com:${NODE2}"
            - "peer0.org3.example.com:${NODE3}"
            - "peer1.org3.example.com:${NODE3}"
            - "peer2.org3.example.com:${NODE3}"
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls:/etc/hyperledger/fabric/tls
            - peer2.org1.example.com:/var/hyperledger/production
        ports:
            - 9051:7051
        mem_limit: '1G'
        cpuset: '7'
        networks:
            - fabric
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - 9090:9090
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on:
            - cadvisor
        networks:
            - fabric

    cadvisor:
        image: gcr.io/google-containers/cadvisor:latest
        container_name: cadvisor
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - fabric

    prom-metrics-collector:
        image: prom-metrics-collector:latest
        container_name: prometheus-metrics-collector
        ports:
            - 5001:5001
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - fabric

    cli:
        container_name: cli
        image: hyperledger/fabric-tools
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            #- FABRIC_LOGGING_SPEC=INFO
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
        extra_hosts:
            - "orderer.example.com:${NODE1}"
            - "peer0.org1.example.com:${NODE1}"
            - "peer1.org1.example.com:${NODE1}"
            - "peer2.org1.example.com:${NODE1}"
            - "peer0.org2.example.com:${NODE2}"
            - "peer1.org2.example.com:${NODE2}"
            - "peer2.org2.example.com:${NODE2}"
            - "peer0.org3.example.com:${NODE3}"
            - "peer1.org3.example.com:${NODE3}"
            - "peer2.org3.example.com:${NODE3}"
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ./chaincode/:/opt/gopath/src/github.com/chaincode
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        depends_on:
            - orderer.example.com
            - peer0.org1.example.com
        networks:
          - fabric
