version: '2'

volumes:
    peer0.org3.example.com:
    peer1.org3.example.com:
    peer2.org3.example.com:

networks:
    fabric:

services:

    ca.org3.example.com:
        image: hyperledger/fabric-ca
        container_name: ca.org3.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org3.example.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/621a83f0af47b5a95261dda849d17bb755c3bfee9bca63133acc93cd1be27c4c_sk
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/621a83f0af47b5a95261dda849d17bb755c3bfee9bca63133acc93cd1be27c4c_sk
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ./crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        networks:
            - fabric

    peer0.org3.example.com:
        container_name: peer0.org3.example.com
        cap_add:
            - NET_ADMIN
        extends:
            file: nodebase.yaml
            service: peer
        environment:
            - CORE_LOGGING_GRPC=DEBUG
            - CORE_PEER_ID=peer0.org3.example.com
            - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.org3.example.com:7052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.org3.example.com:7051
            - CORE_PEER_LOCALMSPID=Org3MSP
        extra_hosts:
            - "orderer.example.com:${NODE1}"
            - "peer0.org1.example.com:${NODE1}"
            - "peer1.org1.example.com:${NODE1}"
            - "peer2.org1.example.com:${NODE1}"
            - "peer0.org2.example.com:${NODE2}"
            - "peer1.org2.example.com:${NODE2}"
            - "peer2.org2.example.com:${NODE2}"
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/etc/hyperledger/fabric/tls
            - peer0.org3.example.com:/var/hyperledger/production
        ports:
            - 7051:7051
        mem_limit: '3G'
        cpuset: '0'
        networks:
            - fabric

    peer1.org3.example.com:
        container_name: peer1.org3.example.com
        cap_add:
            - NET_ADMIN
        extends:
            file: nodebase.yaml
            service: peer
        environment:
            - CORE_LOGGING_GRPC=DEBUG
            - CORE_PEER_ID=peer1.org3.example.com
            - CORE_PEER_ADDRESS=peer1.org3.example.com:7051
            - CORE_PEER_CHAINCODEADDRESS=peer1.org3.example.com:7052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.org3.example.com:7051
            - CORE_PEER_LOCALMSPID=Org3MSP
        extra_hosts:
            - "orderer.example.com:${NODE1}"
            - "peer0.org1.example.com:${NODE1}"
            - "peer1.org1.example.com:${NODE1}"
            - "peer2.org1.example.com:${NODE1}"
            - "peer0.org2.example.com:${NODE2}"
            - "peer1.org2.example.com:${NODE2}"
            - "peer2.org2.example.com:${NODE2}"
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls:/etc/hyperledger/fabric/tls
            - peer1.org3.example.com:/var/hyperledger/production
        ports:
            - 8051:7051
        mem_limit: '2G'
        cpuset: '1'
        networks:
            - fabric

    peer2.org3.example.com:
        container_name: peer2.org3.example.com
        cap_add:
            - NET_ADMIN
        extends:
            file: nodebase.yaml
            service: peer
        environment:
            - CORE_LOGGING_GRPC=DEBUG
            - CORE_PEER_ID=peer2.org3.example.com
            - CORE_PEER_ADDRESS=peer2.org3.example.com:7051
            - CORE_PEER_CHAINCODEADDRESS=peer2.org3.example.com:7052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org3.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.example.com:7051
            - CORE_PEER_LOCALMSPID=Org3MSP
        extra_hosts:
            - "orderer.example.com:${NODE1}"
            - "peer0.org1.example.com:${NODE1}"
            - "peer1.org1.example.com:${NODE1}"
            - "peer2.org1.example.com:${NODE1}"
            - "peer0.org2.example.com:${NODE2}"
            - "peer1.org2.example.com:${NODE2}"
            - "peer2.org2.example.com:${NODE2}"
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/org3.example.com/peers/peer2.org3.example.com/msp:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/org3.example.com/peers/peer2.org3.example.com/tls:/etc/hyperledger/fabric/tls
            - peer2.org3.example.com:/var/hyperledger/production
        ports:
            - 9051:7051
        mem_limit: '1G'
        cpuset: '1'
        networks:
            - fabric

    cadvisor:
        image: gcr.io/google-containers/cadvisor:latest
        container_name: cadvisor
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - fabric

    cli:
        container_name: cli
        image: hyperledger/fabric-tools
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            #- FABRIC_LOGGING_SPEC=DEBUG
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
            - CORE_PEER_LOCALMSPID=Org3MSP
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp
        extra_hosts:
            - "orderer.example.com:${NODE1}"
            - "peer0.org1.example.com:${NODE1}"
            - "peer1.org1.example.com:${NODE1}"
            - "peer2.org1.example.com:${NODE1}"
            - "peer0.org2.example.com:${NODE2}"
            - "peer1.org2.example.com:${NODE2}"
            - "peer2.org2.example.com:${NODE2}"
            - "peer0.org3.example.com:${NODE3}"
            - "peer1.org3.example.com:${NODE3}"
            - "peer2.org3.example.com:${NODE3}"
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ./chaincode/:/opt/gopath/src/github.com/chaincode
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        depends_on:
            - peer0.org3.example.com
        networks:
            - fabric
